### ISSUE TITLE
Connecting to a RAVE study?

### ISSUE THREAD

**Issue by mattkoch614** [mdsol/appconnect-ios#59]
I'm having trouble figuring out how to set this up to properly "connect" to one of our RAVE studies. I was able to follow the README file up until the point where I build and run the project in XCode (which succeeds.)

At this point, the sample iOS app asks the user to either login or create a new account, which is where I'm stuck. How do I modify this sample app to connect to a RAVE study? Do I need to modify one of the project ``*.swift`` files to contain our RAVE subdomain and study name somewhere?

I should mention that if I try to simply use the in-app registration feature, I get the following error:

![image](https://user-images.githubusercontent.com/8203609/39401839-a846060e-4b1d-11e8-8fcb-7b56840d854d.png)

Any help would be greatly appreciated.

**Comment by ncarroll-mdsol** [comment]
Hello!

The documentation may not be very clear about this. The in-app registration is only for non-rave studies.

For Rave studies, Subjects have to be created in Rave, and then linked to a user account via Patient Registration. You can find a step-by-step process here: https://learn.mdsol.com/api/appconnect/accessing-patient-cloud-registration-from-your-study-for-ios-95295815.html

The basic process is:
- Create a Subject in Rave
- Use Patient Cloud Registration to generate an activation code for the Subject
- Use the activation website to create an account for that user
- Login using the newly created account. Then you should see the Patient Cloud-enabled forms in the app.

Let me know if that clears things up or if you have further questions!

**Comment by mattkoch614** [comment]
Thank you, this is helpful. I believe we'll need to ensure we've "turned on" patient cloud registration for the test study we have in mind.

In ``AppDelegate.swift`` - what environment should we be using out of the available options when developing locally? I believe this defaults to ``MDClientEnvironment.sandbox``.

```swift
MDBabbage.start(
    with: MDClientEnvironment.sandbox, 
    apiToken: "some api token", 
    publicDirectory: dir, 
    privateDirectory: dir, 
    encryptionKey: key)
```

**Comment by ncarroll-mdsol** [comment]
Generally you'll be using `.production`, although if this is for a hackathon, it may be `.innovate`.

A simple way to tell is to look at the iMedidata URL that you use to login. If it has an environment as the subdomain (sandbox.imedidata.net, innovate.imedidata.com, etc..) then that is the environment to use. If it does not have one (e.g. imedidata.com) then you'll want `.production`.

One more note - the `apiToken` argument is also used only for non-Rave studies. So if you're using Rave, you can just leave it blank.

**Comment by mattkoch614** [comment]
Thank you @ncarroll-mdsol ! This definitely clears things up for me. I'll close this issue.
